# ------------------------[  ZSH CONFIGURATION ENTRY POINT  ]------------------------ #
# ----------------------------------------------------------------------------------- #
# This file was generated by 'adityastomar67/zsh-conf'.
#
# WARNING: Do not edit the managed config in ~/.config/zsh-conf/zshrc directly.
#          Instead, add your custom settings and overrides in the section below.


# ........................[  1. Interactive Guard  ]........................ #

# Stop here if not running interactively (improves SCP/SFTP speeds)
[[ $- != *i* ]] && return


# ........................[  2. Benchmarking (Start)  ]........................ #

# Enable startup timing if ZSH_BENCHMARK="Yes" in ~/.zshenv

## Start a wall-clock timer (nanoseconds) for total load time precision
## zprof only measures functions; this measures actual file sourcing time.
zmodload zsh/datetime
local time_start=$EPOCHREALTIME

[[ "$ZSH_BENCHMARK" == "Yes" ]] && zmodload zsh/zprof 2>/dev/null


# ------------------------[  3. CORE CONFIGURATION  ]------------------------ #

# Ensure ZSH_PATH is set (fallback to default if missing)
: ${ZSH_PATH:=$HOME/.config/zsh-conf}

local RC="$ZSH_PATH/zsh/zshrc"
[[ "$MINIMALIST" == "Yes" ]] && RC="$ZSH_PATH/zsh/zshrc_mini"  # Minimal config test

# Loading the actual config file
if [[ -r "$RC" ]]; then
    source "$RC"
else
    printf "\n\033[0;31m[ERROR] Critical: Config not found at %s\033[0m\n" "$RC"
    printf "Please try Reinstalling the configuration.\n\n"
    return
fi


# ------------------------[  4. TERMINAL DECORATIONS  ]------------------------ #

#  Random Visuals (Run on every shell start)
if is_installed ColorScript; then
    # Run random ASCII art script
    ColorScript -r
elif (( $+commands[motivate] )); then
    # Run motivational quotes if installed
    motivate && echo
fi


# ------------------------[  5. USER OVERRIDES  ]------------------------ #

# Place your custom aliases, exports, and function overrides below.

## EXAMPLE: Custom Aliases ##
# alias myip="curl http://ipecho.net/plain; echo"

## EXAMPLE: Environment ##
# export PATH="$PATH:$HOME/my-custom-bin"


# ------------------------[  End of User Overrides  ]------------------------ #


# ........................[  6. Benchmarking (Report)  ]........................ #

# Print profile report if benchmarking was enabled
if [[ "$ZSH_BENCHMARK" == "Yes" ]]; then
    local time_end=$EPOCHREALTIME
    # Precision calculation in milliseconds
    local total_ms=$(( (time_end - time_start) * 1000 ))

    printf "\n\033[1;33m--- ⏱️  Startup Benchmark ---\033[0m\n"
    printf "Total Wall-Clock Time: \033[1;32m%.2f ms\033[0m\n" $total_ms

    printf "\nTop 20 Slowest Functions:\n"
    zprof | head -20
    echo "-----------------------------------------------------------------------------------"
fi

