# ------------------------[  ZSH CONFIGURATION ENTRY POINT  ]------------------------ #
# This file was generated by 'adityastomar67/zsh-conf'.
#
# WARNING: Do not edit the managed config in ~/.config/zsh-conf/zshrc directly.
# Instead, add your custom settings and overrides in the section below.


# ........................[  1. Interactive Guard  ]........................ #
# Stop here if not running interactively (improves SCP/SFTP speeds)
[[ $- != *i* ]] && return


# ........................[  2. Benchmarking (Start)  ]........................ #
# Enable startup timing if ZSH_BENCHMARK=1
[[ "$ZSH_BENCHMARK" == "1" ]] && zmodload zsh/zprof


# ------------------------[  3. CORE CONFIGURATION  ]------------------------ #

# Source the main configuration engine
if [[ -r "$ZSH_PATH/zsh/zshrc" ]]; then
    source "$ZSH_PATH/zsh/zshrc"
else
    printf "\n\033[0;31m[ERROR] Critical: Main config not found at %s/zsh/zshrc\033[0m\n" "$ZSH_PATH"
    printf "Please try reinstalling the configuration.\n\n"
fi


# ------------------------[  4. TERMINAL DECORATIONS  ]------------------------ #

# A. Installation Warning (Runs only once after install)
if [[ -n "$SHOW_CONFIG_WARNING" ]]; then
    # Define temporary color variables for readability
    local R=$'\e[1;31m'  # Red
    local B=$'\e[34m'    # Blue
    local U=$'\e[4m'     # Underline
    local N=$'\e[0m'     # Reset

    printf "\n"
    printf "${R}[#IMP] ${B}Do not edit the main config file directly ${N}${U}~/.config/zsh-conf/zshrc${N}\n"
    printf "       ${B}Instead, add any setting overrides in this file ${N}${U}~/.zshrc${N}\n\n"

# B. Random Visuals (Run on every shell start)
elif [[ -x "$HOME/.local/bin/colorscript" ]]; then
    # Run random ASCII art script (distro-tube/dt-colorscripts)
    "$HOME/.local/bin/colorscript" -r
elif command -v motivate >/dev/null; then
    # Run motivational quotes if installed
    motivate && echo
fi


# ------------------------[  5. USER OVERRIDES  ]------------------------ #
# Place your custom aliases, exports, and function overrides below.

## EXAMPLE: Custom Aliases ##
# alias myip="curl http://ipecho.net/plain; echo"

## EXAMPLE: Environment ##
# export PATH="$PATH:$HOME/my-custom-bin"


# ------------------------[  End of User Overrides  ]------------------------ #


# ........................[  6. Benchmarking (Report)  ]........................ #
# Print profile report if benchmarking was enabled
if [[ "$ZSH_BENCHMARK" == "1" ]]; then
    printf "\n--- Startup time report ---\n"
    zprof | head -20
fi
