#    ░░░░▀▀█░█▀▀░█░█░█▀▄░█▀▀
#    ░░░░▄▀░░▀▀█░█▀█░█▀▄░█░░
#    ░▀░░▀▀▀░▀▀▀░▀░▀░▀░▀░▀▀▀

# ------------------------------------------------------------------------------
# File Purpose
#   This is the primary entry point for the interactive Zsh configuration.
#   It orchestrates the loading of core settings, plugins, and user overrides.
#
# Features / Responsibilities
#   - Interactive Session Guard.
#   - Startup Profiling (Benchmarking).
#   - Dynamic Configuration Sourcing.
#   - User Customization Injection.
#
# This file was generated by 'adityastomar67/zsh-conf'.
#
# WARNING: Do not edit the managed config in ~/.config/zsh-conf/zshrc directly.
#          Instead, add your custom settings and overrides in the section below.
#
# Project: Zsh-conf
# ------------------------------------------------------------------------------

#

# 1. Interactive Session Guard
# ─────────────────────────────────────────────────────────────
## We immediately check if the shell is interactive. If it's a background
## process (like scp, sftp, or a script), we exit to prevent errors and
## speed up connections.

[[ $- != *i* ]] && return


# 2. Benchmarking Initialization
# ─────────────────────────────────────────────────────────────
## If profiling is enabled in .zshenv, we start the timer here.
## We use Zsh's internal datetime module for nanosecond precision.

# Load the datetime module to access $EPOCHREALTIME
zmodload zsh/datetime

# Capture the wall-clock start time
local _startup_timer_start=$EPOCHREALTIME

# Load the zprof module if benchmarking is explicitly requested
[[ "$ZSH_BENCHMARK" == "Yes" ]] && zmodload zsh/zprof 2>/dev/null


# 3. Core Configuration Loader
# ─────────────────────────────────────────────────────────────
## Determines which configuration profile to load (Minimal vs Full)
## and sources the actual logic files.

# ── profile selection ──────────────────────────────────────────────────

# Check if "Minimal Mode" is enabled (Useful for older hardware or root users)
[[ "$ENABLE_MINIMAL_MODE" == "Yes" ]] && RC="$ZSH_CONFIG_ROOT/zshrc.mini" || RC="$ZSH_CONFIG_ROOT/zshrc"


# ── execution ──────────────────────────────────────────────────────────

if [[ -r "$RC" ]]; then
    source "$RC"
else
    # !!! CRITICAL: Configuration file missing
    printf "\n\033[0;31m[ERROR] Critical: Config not found at %s\033[0m\n" "$RC"
    printf "Please try reinstalling the configuration.\n\n"
    return
fi


# 4. Terminal Decorations
# ─────────────────────────────────────────────────────────────
## Adds visual flair to the terminal startup.
## Randomly selects between color scripts or motivational quotes if enabled.

#

if [[ "$ENABLE_FANCY_STARTUP" == "Yes" ]]; then
    local -a available_visual_commands=()

    # Check for installed visualization tools
    (( $+commands[ColorScript] )) && available_visual_commands+=( "ColorScript -r" )
    (( $+commands[motivate] ))    && available_visual_commands+=( "motivate" )

    # Select and execute a random visual if any are found
    if (( ${#available_visual_commands} > 0 )); then
        # Pick random index (1-based)
        local random_idx=$(( RANDOM % ${#available_visual_commands} + 1 ))

        # Execute the command
        ${=available_visual_commands[$random_idx]}

        # Add visual spacing
        echo
    fi
fi


# 5. User Overrides
# ─────────────────────────────────────────────────────────────
## This section is reserved for YOUR custom settings.
## Anything defined here will override the managed configuration above.

# ------------------------------------------------------------------------------
# Custom Aliases
# alias myip="curl http://ipecho.net/plain; echo"

# ------------------------------------------------------------------------------
# Environment Variables
# export PATH="$PATH:$HOME/my-custom-bin"

# ------------------------------------------------------------------------------
# Function Overrides


# ------------------------------------------------------------------------------


# 6. Benchmarking Report
# ─────────────────────────────────────────────────────────────
## Calculates the total execution time and displays the results.
## This block must be the very last thing in the file.

if [[ "$ZSH_BENCHMARK" == "Yes" ]]; then
    # 1. STOP THE CLOCK
    #    We capture time immediately to exclude the UI rendering logic from the score.
    local _startup_timer_end=$EPOCHREALTIME

    # Calculate duration in milliseconds
    local total_duration_ms=$(( (_startup_timer_end - _startup_timer_start) * 1000 ))

    # 2. Load the Benchmark UI
    local BENCH_UI="$ZSH_CONFIG_ROOT/lib/_ui.benchmark"

    if [[ -r "$BENCH_UI" ]]; then
        source "$BENCH_UI"
    else
        # ---- SAFE: Fallback if UI file is missing
        echo "Benchmark UI file not found at: $BENCH_UI"
        echo "Total startup time: ${total_duration_ms}ms"
    fi
fi
